stage: prod  # name your stage here (e.g. prod, dev, stage, playground)
secret_file_path: ./secrets/prod/secrets.yaml  # Pfad zur Secret-Datei
ca_name: example_ROOT # die CA mit der signiert werden soll!
